"""Add user preferences

Revision ID: 13ca10dc6ad0
Revises: d8de0d284aeb
Create Date: 2025-12-06 22:03:36.676585+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ca10dc6ad0'
down_revision = 'd8de0d284aeb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    # ### end Alembic commands ###
